# 七、Python 和 GTK+

现在，您已经对 GTK+ 和一些简单的小部件有了合理的理解，是时候了解 Python 和 GTK+ 如何协同工作的细节了。我们还涵盖了对您的项目有用的其他 Python 方面，以及一些有用的 PGObject 库。

虽然这本书不是 Python 的全面指南，但我们研究了 GTK+ 使用的几个主题，这些主题通常不会被基本的 Python 编程指南所涵盖。

## 参数和关键字参数

在整个 GTK+ 库中，使用关键字参数和自变量将类实例属性值从类传递到子类，等等。所以让我们仔细研究一下这个现象。

关于 GTK+ 类属性，需要理解的最重要的一点是，它们在 PyGTK 中是作为 Python 属性实现的。这意味着在访问时，对属性类和方法的引用应该替换为标准的 Python 类和方法。以下示例显示了如何访问名为`title`的`Gtk.Window`属性。

```py
win = Gtk.Window()
title = win.props.title

```

也可以使用标准 Python 方法设置属性。

```py
win = Gtk.Window()
win.props.title = "My Main Window"

```

当然，`Gtk.Window`类也提供了`get_title()`和`set_title()`方法来执行相同的任务，但是快捷的 Python 方法也执行相同的任务。选择使用哪种方法完全取决于你自己。

现在您已经理解了 GTK+ 属性是作为 Python 属性实现的，我们可以继续描述如何使用关键字参数并将其传递给类。让我们继续看看`Gtk.Window`以及如何创建该类的实例。`Gtk.Window`的类定义如下:

```py
class Gtk.Window(Gtk.Bin):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

```

那么，这些`*args`和`**kwargs`自变量/参数是什么，它们做什么？PyGTK 使用这种方法将属性名和值传递给类实例。当一个类实例收到这些参数时，它可以选择使用它们，将它们传递给`super`类，或者直接丢弃它们。大多数情况下，它使用与类定义的属性相匹配的属性。然后，它定位相应的值，并将其赋给相应的属性名。它使用类似于清单 7-1 中的代码来完成这项任务。

```py
class MyWindow(Gtk.Window):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for arg in argv:
            print("Another arg through *argv :",arg) for kw in keywords:
            print(kw, ":", keywords[kw])

Listing 7-1Keyword Arguments

```

示例中没有显示形式参数。参数有一个必需的顺序:形式参数必须首先出现在参数列表中，然后是所有的`args`参数，最后是所有的关键字参数。下面的例子展示了如何工作的正式声明。

```py
function(formal_args, args, kwargs)

```

下面是使用形式参数、变量参数和关键字参数的调用语句。

```py
# function using formal and variable args def function1(title, modal, *args):

# calling function1
function1("My title", False, # variable args follow
          "Peaches", "and", "Cream")
function1("My Window", True) # Only formal args, no variable args
function1(True)              # Invalid!!! Missing one formal arg

# function using formal and keyword args def function2(title, modal, **kwargs)

# calling function2
function2("My title", True, parent=window, accept_focus=True) function2("My Window", False) # Only formal args, no keyword args
function2(parent=window)      # Invalid, no formal args

```

这些例子还有许多其他的变化，但是如果你遵循这三个简单的规则，你应该没有问题处理所有的变化:

*   形式参数必须首先出现在参数列表中。如果没有形式参数，那么它们可以从参数列表中消失。你需要多少正式论点就有多少。

*   变量参数必须全部出现在参数列表的下一个位置。如果没有可变参数，那么它们可以从参数列表中消失。可以有任意多的变量参数。

*   关键字参数必须全部出现在参数列表的最后。如果没有关键字参数，那么它们可以不在参数列表中。可以有任意多的关键字参数。

PyGTK 很少使用形式参数；它几乎只使用变量和关键字参数。这使得处理所有 GTK+ 类的实例化变得更加容易。请记住，GTK+ 忽略任何关键字参数，这些关键字参数是属性名*而不是属性名*。当您想要建立和管理自己的属性时，这非常有用。

## 记录

日志记录跟踪软件运行时发生的事件。软件开发人员将日志调用添加到他们的代码中，以指示某些事件已经发生。事件由描述性消息来描述，该描述性消息可以可选地包含可变数据(即，对于事件的每次发生可能不同的数据)。事件也具有开发者赋予事件的重要性；重要性也可称为*级别*或*严重性*。

### 何时使用日志记录

日志记录为简单的日志记录用法提供了一组方便的函数。这些是`debug()`、`info()`、`warning()`、`error()`和`critical()`。表 7-1 描述了何时对常见任务使用日志记录，以及对每项任务使用的最佳工具。

表 7-1

日志记录任务

<colgroup><col class="tcol1 align-left"> <col class="tcol2 align-left"></colgroup> 
| 

您要执行的任务

 | 

任务的最佳工具

 |
| --- | --- |
| 命令行脚本或程序的普通用途的显示控制台输出 | `print()` |
| 报告程序正常运行期间发生的事件(例如，状态监控或故障调查) | [`logging.info`](http://logging.info) `()`(或`logging.debug()`用于诊断目的的非常详细的输出) |
| 针对特定运行时事件发出警告 | 如果客户端应用对这种情况无能为力，但仍应记录该事件 |
| 报告特定运行时事件的错误 | 引发异常 |
| 报告抑制错误而不引发异常(例如，长时间运行的服务器进程中的错误处理程序) | `logging.error()`、`logging.exception()`或`logging.critical()`，视具体误差和应用领域而定 |

日志记录功能是根据它们所跟踪的事件的级别或严重性来命名的。表 7-2 中描述了标准等级及其适用性(按严重程度递增)。

表 7-2

日志记录级别

<colgroup><col class="tcol1 align-left"> <col class="tcol2 align-left"></colgroup> 
| 

水平

 | 

用的时候

 |
| --- | --- |
| 调试 | 详细信息，通常仅在诊断问题时感兴趣。 |
| 信息 | 确认事情按预期运行。 |
| 警告 | 表明发生了意想不到的事情，或预示着不久的将来会出现一些问题(例如，磁盘空间不足)。该软件仍按预期工作。 |
| 错误 | 由于更严重的问题，软件无法执行功能。 |
| 批评的 | 一个严重错误，表明程序本身可能无法继续运行。 |

默认级别是警告，这意味着只有该级别及以上的事件才会被跟踪，除非日志记录包配置为其他级别。

可以用不同的方式处理被跟踪的事件。处理跟踪事件的最简单方法是将它们打印到控制台。另一种常见的方法是将它们写入磁盘文件。

### 一些简单的例子

下面是一个非常简单的例子。

```py
import logging

logging.warning('Watch out!') # will print a message to the console logging.info('I told you so') # will not print anything

```

如果您在脚本中键入这些行并运行它，您会在控制台上看到以下内容。

```py
WARNING:root:Watch out!

```

因为默认级别是警告，所以不显示信息消息。打印的消息包括记录调用中提供的级别指示和事件描述(即，小心！).现在不要担心“根”的部分；后面会解释。如果需要的话，实际输出的格式可以非常灵活；稍后还会解释格式化选项。

### 记录到文件

在一个文件中记录日志事件是非常常见的，所以接下来让我们来看看。确保在新启动的 Python 解释器中尝试以下操作；不要只是从前面描述的会话继续。

```py
import logging

logging.basicConfig(filename='example.log',level=logging.DEBUG)
logging.debug('This message should go to the log file')
logging.info('So should this')
logging.warning('And this, too')

```

现在，如果我们打开文件，看看我们有什么，我们应该会找到日志消息。

```py
DEBUG:root:This message should go to the log file INFO:root:So should this WARNING:root:And this, too

```

该示例还展示了如何设置日志记录级别，该级别充当跟踪的阈值。在这种情况下，因为我们将阈值设置为 DEBUG，所以所有的消息都被打印出来。

如果您想从命令行选项设置日志记录级别，例如

```py
--log=INFO

```

并且在一个`loglevel`变量中有传递给`--log`的参数值，您可以使用

```py
getattr(logging, loglevel.upper())

```

获取值，通过 level 参数传递给`basicConfig()`。

您可能希望对任何用户输入值进行错误检查，如下例所示。

```py
# assuming loglevel is bound to the string value obtained from the
# command line argument. Convert to upper case to allow the user to
# specify --log=DEBUG or --log=debug
numeric_level = getattr(logging, loglevel.upper(), None)
if not isinstance(numeric_level, int):
    raise ValueError('Invalid log level: %s' % loglevel)
logging.basicConfig(level=numeric_level, ...)

```

对`basicConfig()`的调用应该在对`debug()`、`info()`等等的任何调用之前。因为它旨在作为一次性的简单配置工具，只有第一次调用实际上做了什么；随后的呼叫实际上是无效的。

如果多次运行前面的脚本，连续运行的消息将被附加到`example.log`文件中。如果您希望每次运行都重新开始，而不是记住以前运行的消息，您可以指定`filemode`参数，将示例中的调用改为:

```py
logging.basicConfig(filename='example.log', filemode="w", level=logging.DEBUG)

```

输出与之前相同，但是不再附加日志文件，因此来自早期运行的消息会丢失。

### 从多个模块记录日志

如果您的程序由多个模块组成，下面是一个如何组织日志记录的示例。

```py
# myapp.py
# import logging
# import mylib

def main():
    logging.basicConfig(filename='myapp.log', level=logging.INFO)
    logging.info('Started')
    mylib.do_something()
    logging.info('Finished')

if __name__ == '__main__':
    main()

# mylib.py
import logging

def do_something():
logging.info('Doing something')

```

如果您运行`myapp.py`，您应该在`myapp.log`中看到这个:

```py
INFO:root:Started INFO:root:Doing something INFO:root:Finished

```

这可能是你期望看到的。您可以使用`mylib.py`中的模式将其推广到多个模块。注意，对于这个简单的使用模式，除了查看事件描述之外，通过查看日志文件，您不会知道您的消息来自应用的什么地方。如果你想跟踪你的消息的位置，你需要参考超出本教程水平的文档。

### 记录可变数据

若要记录变量数据，请使用事件描述消息的格式字符串，并将变量数据作为参数追加。例如，

```py
import logging

logging.warning('%s before you %s', 'Look', 'leap!')

```

显示

```py
WARNING:root:Look before you leap!

```

如您所见，将变量数据合并到事件描述消息中使用了旧的`%`样式的字符串格式。这是为了向后兼容；日志包早于更新的格式选项，比如`str.format()`和`string.Template`。这些更新的格式选项是受支持的，但是探究它们超出了本书的范围。有关详细信息，请参阅 Python 文档。

### 更改显示消息的格式

要更改用于显示消息的格式，您需要指定要使用的格式。

```py
import logging

logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.DEBUG)
logging.debug('This message should appear on the console')
logging.info('So should this')
logging.warning('And this, too')

```

这应该会打印出如下内容。

```py
2010-12-12 11:41:42,612 is when this event was logged.

```

日期/时间显示的默认格式是 ISO8601 或[RFC 3339]。如果您需要对日期/时间的格式进行更多的控制，请为`basicConfig()`提供一个`datefmt`参数，如下所示。

```py
import logging

logging.basicConfig(format='%(asctime)s %(message)s', datefmt='%m/%d/%Y %I:%M:%S % logging.warning('is when this event was logged.')

```

这将显示如下内容。

```py
12/12/2010 11:46:36 AM is when this event was logged.

```

`datefmt`参数的格式与`time.strftime()`支持的格式相同。

## 例外

在 GTK+，application 中运行异常和运行任何标准 Python 程序是一样的。因为 GTK 模块只是一个包装了 GTK+API 的标准 Python 模块，所以库实现将所有 GTK+ 异常都变成了标准 Python 异常。这样做的结果是您不需要担心捕获`Glib.Error`错误。没有一个会被 GTK 模块抛出。

这并不意味着您可以忽略标准的 Python 异常。您应该为应用中的任何异常做好准备，就像您为任何 Python 应用所做的那样。让我们回顾一下 Python 异常的一些原则。

### 引发异常

当应用出错时，异常会自动引发。在我们了解如何处理异常之前，让我们先看看如何手动引发异常，甚至创建自己的异常。

#### 加薪声明

您用`raise`语句引发一个异常，该语句接受一个类(它应该是`Exception`类的子类)或一个实例的参数。当使用类作为参数时，会自动创建该类的一个实例。下面是一个使用内置`Exception`类的例子。

```py
>>> raise Exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception
> raise Exception('overload') Traceback (most recent call last):
  File "<stdin>", line 1, in <module> Exception: overload

```

第一个例子引发了一个普通的异常，没有关于出错的信息。第二个示例添加了错误消息重载。

许多内置类是可用的。在 Python 库参考的“内置异常”一节中可以找到所有异常类的完整描述。下面列出了所有 Python 3.x 异常的类层次结构。

```py
BaseException
 +-- SystemExit
 +-- KeyboardInterrupt
 +-- GeneratorExit
 +-- Exception
      +-- StopIteration
      +-- StopAsyncIteration
      +-- ArithmeticError
      |    +-- FloatingPointError
      |    +-- OverflowError
      |    +-- ZeroDivisionError
      +-- AssertionError
      +-- AttributeError
      +-- BufferError
      +-- EOFError
      +-- ImportError
      |    +-- ModuleNotFoundError
      +-- LookupError
      |    +-- IndexError
      |    +-- KeyError
      +-- MemoryError
      +-- NameError
      |    +-- UnboundLocalError
      +-- OSError
      |    +-- BlockingIOError
      |    +-- ChildProcessError
      |    +-- ConnectionError
      |    |    +-- BrokenPipeError
      |    |    +-- ConnectionAbortedError
      |    |    +-- ConnectionRefusedError
      |    |    +-- ConnectionResetError
      |    +-- FileExistsError
      |    +-- FileNotFoundError
      |    +-- InterruptedError
      |    +-- IsADirectoryError
      |    +-- NotADirectoryError
      |    +-- PermissionError
      |    +-- ProcessLookupError
      |    +-- TimeoutError
      +-- ReferenceError
      +-- RuntimeError
      |    +-- NotImplementedError
      |    +-- RecursionError
      +-- SyntaxError
      |
           +-- IndentationError
      |         +-- TabError
      +-- SystemError
      +-- TypeError
      +-- ValueError
      |    +-- UnicodeError
      |         +-- UnicodeDecodeError
      |         +-- UnicodeEncodeError
      |         +-- UnicodeTranslateError
      +-- Warning
           +-- DeprecationWarning
           +-- PendingDeprecationWarning
           +-- RuntimeWarning
           +-- SyntaxWarning
           +-- UserWarning
           +-- FutureWarning
           +-- ImportWarning
           +-- UnicodeWarning
           +-- BytesWarning
           +-- ResourceWarning

```

#### 自定义异常类

有很多内置的异常，涵盖了很多领域。但是有时候你可能想创建自己的异常类。例如，没有 GTK+ 异常类，所以您可能需要创建自己的异常类。这使您有机会根据异常的类有选择地处理异常。因此，如果您想处理 GTK 运行时错误，您将需要一个单独的异常类。

您可以像创建任何其他类一样创建这样的异常，但是一定要创建`Exception`类的子类(直接或间接，这意味着可以创建任何其他内置异常的子类)。下面演示如何编写自定义异常类。

```py
class GtkCustomException)Exception): pass

```

如果需要的话，可以随意在类中添加自己的方法。

### 捕捉异常

当然，引发异常只是异常的第一部分。真正有用的部分是在您自己的应用代码中捕捉(或捕获)和处理异常。您可以使用`try`和`except`语句来实现这一点。让我们看一个简单的例子。

```py
x = input('Enter the first number: ')
y = input('Enter the second number: ')
print(x/y)

```

直到用户输入零作为第二个数字。

```py
Enter the first number: 10
Enter the second number: 0
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ZeroDivisionError: division by zero

```

为了捕捉异常并执行一些错误处理(比如打印一个更友好的错误消息)，您可以像这样重写程序:

```py
try:
    x = input('Enter the first number: ')
    y = input('Enter the second number: ')
    print(x/y)
except ZeroDivisionError:
    print('The second number can not be zero!')

```

虽然对于这样一个简单的例子来说，这个解决方案看起来有些夸张，但是当在整个应用中使用数百个 division 语句时，这将是一个更合理的例子。

### 注意

异常从函数和方法传播到它们被调用的地方，如果它们也没有被捕获，异常将“冒泡”到程序的顶层。这意味着您可以使用`try`和`except`语句来捕捉您自己和他人的代码(模块、函数、类等)中出现的异常。).

### 引发和重新引发异常

异常可以在其他异常内部引发，将异常传递给更高级别的代码。为此，必须通过`raise`语句不带任何参数地调用后续异常。

下面是这种非常有用的技术的一个例子。如果异常没有被抑制，该示例将`ZeroDivisionException`传递给更高级别的代码。

```py
class SuppressedDivision:
    suppressed = False
    def calc(self, expr):
        try:
            return eval(expr)
        except ZeroDivisionError:
            if self.suppressed:
                print('Division by zero is illegal!')
            else:
                raise

```

正如您所看到的，当计算没有被取消时，`ZeroDivisionException`被捕获，但是被传递到更高级别的代码，在那里它将被捕获和处理。

### 捕捉多个异常

`try`和`except`块也可以捕捉和处理多个异常。为了了解这是如何工作的，让我们增强前面的例子来捕捉`TypeError`异常。

```py
class SuppressedDivision:
    suppressed = False
    def calc(self, expr):
        try:
            return eval(expr)
        except ZeroDivisionError:
            if self.suppressed:
                print('Division by zero is illegal!')
            else:
                raise
        except TypeError:
            if self.suppressed:
                print('One of the operands was not a valid number!')
            else:
                raise

```

现在我们开始看到`try`和`except`代码块以及使用异常的威力。在前面的例子中，我们使用解释器的能力来检查计算的所有变量，而不是我们自己编写基本相同的代码来处理所有变量，以便在我们处理它之前发现计算是否有效。

我们还可以将这两个异常合并到一个代码块中，如下所示。

```py
class SuppressedDivision:
    suppressed = False
    def calc(self, expr):
        try:
            return eval(expr)
        except ZeroDivisionError, TypeError:
            if self.suppressed:
                print('One or both operands is illegal!')
            else:
                raise

```

我们还可以捕获导致异常的对象。

```py
class SuppressedDivision:
    suppressed = False
    def calc(self, expr):
        try:
            return eval(expr)
        except (ZeroDivisionError, TypeError_, e:
            if self.suppressed:
                print('The value "' + str(e) '" is illegal!')
            else:
                raise

```

处理异常还有更多的内容，但是这些信息足以激起您的兴趣。

有关异常的更完整信息，请参考 Python 资源。